### ISSUE TITLE
Fine-grained update of configuration

### ISSUE THREAD

**Issue by archerzz** [IBM-Cloud/bluemix-cli-sdk#75]
# Problem
Right now we always write the whole configuration to the configuration file, regardless of whether each individual property has been modified or not. That's not good for compatibility. If a plugin uses an old SDK to set a property, it could remove new properties introduced in new version of SDK. Thus causes unexpected error.

# Solution
To improve the compatibility, we should only update the properties which have been modified.

**Comment by weieigao** [comment]
It's dangerous to only update part of the configuration file, especially when the plugin is using an incompatible SDK. 
But according to the offline discussion, we've agreed on to only update tokens in token refresh case. I'll close the issue  since the work is done.
